"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

'''
APP = ['rank.py']
DATA_FILES = [('', ['proxy.txt'])]
OPTIONS = {'argv_emulation': True, 'iconfile': 'data.ico'}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app', 'requests', 'selenium', 'wx'],
)
'''

APP = ['getRank.py']
DATA_FILES = []
OPTIONS = {'argv_emulation': True}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
